#!/usr/bin/env python3
"""Wraps src/<slug>.html fragments into tools/<slug>/index.html with the shared shell.
Fragment format: first line  <!-- title: ... | desc: ... [| js: decoders] -->  then body HTML + <script>.
Also refreshes the generated <head> metadata (favicons, canonical, Open Graph, JSON-LD) of the hand-written pages
between <!-- meta:start --> and <!-- meta:end -->, and writes sitemap.xml and robots.txt."""
import pathlib, re, html, json

ROOT = pathlib.Path(__file__).parent
SITE = "https://tools.kintoyyy.com/"   # public base URL (see CNAME) for canonical links, Open Graph images and the sitemap
NAME = "NetOps Toolkit"
LICENSE_URL = "https://github.com/Kintoyyy/netops-toolkit/blob/main/LICENSE"
STATIC = {"index.html": "", "split/index.html": "split/", "disclaimer/index.html": "disclaimer/", "tools/lookalike-domains/index.html": "tools/lookalike-domains/"}

def head_meta(title, desc, path):
    """Icons, manifest, canonical, social preview and structured data for the page at SITE + path."""
    up, url = "../" * path.count("/"), SITE + path
    t, d, name = html.escape(title), html.escape(desc), title.split(" · ")[0]
    kind = "WebSite" if not path else "WebApplication" if path.startswith("tools/") else "WebPage"
    ld = {"@context": "https://schema.org", "@type": kind, "name": name, "description": desc, "url": url}
    if kind == "WebApplication":
        ld.update(applicationCategory="UtilitiesApplication", operatingSystem="Any (web browser)", browserRequirements="Requires JavaScript",
                  isAccessibleForFree=True, license=LICENSE_URL, offers={"@type": "Offer", "price": "0", "priceCurrency": "USD"},
                  isPartOf={"@type": "WebSite", "name": NAME, "url": SITE})
    else:
        ld["license"] = LICENSE_URL
    return f"""<!-- meta:start (generated by build.py) -->
<link rel="canonical" href="{url}">
<link rel="icon" href="{up}favicon.ico" sizes="32x32">
<link rel="icon" href="{up}assets/icons/icon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="{up}assets/icons/apple-touch-icon.png">
<link rel="manifest" href="{up}site.webmanifest">
<meta name="theme-color" content="#f6f7f9" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#0f1216" media="(prefers-color-scheme: dark)">
<meta name="author" content="Kent Rato">
<link rel="license" href="{LICENSE_URL}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="{NAME}">
<meta property="og:title" content="{t}">
<meta property="og:description" content="{d}">
<meta property="og:url" content="{url}">
<meta property="og:image" content="{SITE}assets/og-image.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="NetOps Toolkit — your network toolbox, in the browser">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{t}">
<meta name="twitter:description" content="{d}">
<meta name="twitter:image" content="{SITE}assets/og-image.png">
<script type="application/ld+json">{json.dumps(ld, ensure_ascii=False).replace("</", "<\\/")}</script>
<!-- meta:end -->"""

TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} · NetOps Toolkit</title>
<meta name="description" content="{desc}">
{meta}
<link rel="stylesheet" href="../../assets/style.css">
</head>
<body>
<div class="wrap">
  <a class="back" href="../../">← All tools</a>
  <header class="top">
    <div><h1>{title}</h1><p class="sub">{desc}</p></div>
    <div class="hdr-actions"><a class="btn split-link" href="../../split/?add={slug}" title="Use this tool side by side with others"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="vertical-align:-3px"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M12 4v16"/></svg> Split view</a><button id="themeBtn" title="Toggle theme"></button></div>
  </header>
<script src="../../assets/common.js"></script>
<script src="../../assets/history.js"></script>
<script src="../../assets/consent.js"></script>
{extra}{body}
<footer>Free and open source under the <a href="https://github.com/Kintoyyy/netops-toolkit/blob/main/LICENSE" target="_blank" rel="noopener">MIT License</a> · provided as is, without warranty · <a href="../../disclaimer/">Disclaimer</a></footer>
</div>
</body>
</html>
"""

for src in sorted((ROOT / "src").glob("*.html")):
    text = src.read_text(encoding="utf-8")
    m = re.match(r"<!--\s*title:\s*(.*?)\s*\|\s*desc:\s*(.*?)\s*(?:\|\s*js:\s*(.*?)\s*)?-->\n", text)
    assert m, f"missing header in {src}"
    out = ROOT / "tools" / src.stem / "index.html"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(TEMPLATE.format(title=html.escape(m[1]), desc=html.escape(m[2]), slug=src.stem, body=text[m.end():],
        meta=head_meta(f"{m[1]} · {NAME}", m[2], f"tools/{src.stem}/"),
        extra=''.join(f'<script src="../../assets/{j.strip()}.js"></script>\n' for j in (m[3] or '').split(',') if j.strip())), encoding="utf-8")
    print("built", out.relative_to(ROOT))

# hand-written pages: refresh the generated block (or add it after the description on first run)
MARK = re.compile(r"<!-- meta:start.*?<!-- meta:end -->", re.S)
for rel, path in STATIC.items():
    f = ROOT / rel
    text = f.read_text(encoding="utf-8")
    title = html.unescape(re.search(r"<title>(.*?)</title>", text, re.S)[1])
    desc = html.unescape(re.search(r'<meta name="description" content="(.*?)">', text)[1])
    block = head_meta(title, desc, path)
    new = MARK.sub(lambda _: block, text, count=1) if MARK.search(text) else \
        re.sub(r'(<meta name="description" content=".*?">\n)', lambda d: d[1] + block + "\n", text, count=1)
    if new != text:
        f.write_text(new, encoding="utf-8")
        print("meta ", rel)

# sitemap.xml + robots.txt
tools = set(re.findall(r"href: 'tools/([^/']+)/'", (ROOT / "assets" / "tools.js").read_text(encoding="utf-8")))
pages = ["", "split/", "disclaimer/"] + [f"tools/{t}/" for t in sorted(tools)]
(ROOT / "sitemap.xml").write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    + "".join(f"  <url><loc>{SITE}{p}</loc></url>\n" for p in pages) + "</urlset>\n", encoding="utf-8")
(ROOT / "robots.txt").write_text(f"User-agent: *\nAllow: /\n\nSitemap: {SITE}sitemap.xml\n", encoding="utf-8")
print("wrote sitemap.xml", len(pages), "pages, robots.txt")
